---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-webhook
  labels:
    app: vault-webhook
webhooks:
  - name: vault.abide.com 
    clientConfig:
      service:
        name: vault-webhook
        namespace: default
        path: "/mutate"
      caBundle: ${CA_CERT}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    # namespaceSelector:
    #   matchLabels:
    #     vault-webhook: enabled